# Generated by Django 2.2 on 2019-05-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(db_index=True, default='Zaporizhia', max_length=150),
            preserve_default=False,
        ),
    ]
